modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
authors = "${authors}"
description = '''
${modDescription}
'''
logoFile = "assets/${modId}/icon.png"

[[dependencies.${modId}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${modId}.mixins.json"

[[mixins]]
config = "${modId}.mixins.neoforge.json"
